POST http://localhost:8080/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="multipartFile"; filename="test.jpg"
Content-Type: image/jpeg

< ./test.jpg
--WebAppBoundary--
