language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp image-api-interface/build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/image-api-interface.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: silencer-examples-builds
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: silencer-examples-builds
    key: image-api-interface.zip
    bundle_type: zip
    application: silencer-codedeploy-silencer-was
    deployment_group: silencer-codedeploy-silencer-was-group
    region: ap-northeast-2
    wait-until-deployed: true

notifications:
  email:
    recipients:
      - silencerwon@gmail.com