language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean image-api-interface:build"

notifications:
  email:
    recipients:
      - silencerwon@gmail.com